error_results/gpt-4-turbo__outputs/772_veri-titan_tmp_tmpbg2iy0kf_spec_crypto_fntt512_no_hints.dfy(5,18): Error: module ct_std2rev_model does not exist
  |
5 |     import opened ct_std2rev_model
  |                   ^^^^^^^^^^^^^^^^