error_results/gpt-3.5-turbo__outputs/773_veribetrkv-osdi2020_tmp_tmpra431m8q_docker-hdd_src_veribetrkv-linear_lib_Base_SetBijectivity_no_hints.dfy(35,22): Error: second argument to "in" must be a set, multiset, or sequence with elements of type ((A, B), B), or a map with domain ((A, B), B) (instead got iset<(A, B)>) (expecting element type to be assignable to (A, B) (got ((A, B), B)))
   |
35 |         assert (p, b) in relation;
   |                       ^^

error_results/gpt-3.5-turbo__outputs/773_veribetrkv-osdi2020_tmp_tmpra431m8q_docker-hdd_src_veribetrkv-linear_lib_Base_SetBijectivity_no_hints.dfy(32,41): Error: incorrect argument type at index 0 for datatype constructor parameter '0' (expected A, found (A, B))
   |
32 |         ensures exists p :: p in line && (p, b) in relation
   |                                          ^